import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/page"; 
import NavBar from "@/components/NavBar/page";
import Slide from "@/components/Slide"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GSMT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-400 text-white p-4">
          <Header />
          
        </header>
        <NavBar />

        <Slide />
        <main className="min-h-screen p-6">{children}</main>

        <footer className="bg-gray-200 text-center p-4">
          © 2025 Government of Andhra Pradesh
        </footer>
      </body>
    </html>
  );
}
